### ISSUE TITLE
嵌套vipwPager时，有没有滑动冲突？

### ISSUE THREAD

**Issue by jingzz1** [Bamboy120315/SlidingShut#2]
嵌套viewPager,recyclerView，右滑时有冲突吗？

**Comment by Bamboy120315** [comment]
不会的，我用的是强拦截，并且只会影响屏幕最左侧的三十分之一的区域，希望能帮到你，如果还有问题，为了方便，可以加Q群：569614530，群里找我，昵称尘少

**Comment by jingzz1** [comment]
我已经在群里了……
这方法确实有用，但仅仅在最左侧滑动才能退出毕竟不实用，目前我在你代码的基础上解决了viewPager和recyclerView的滑动冲突，还有一个HorizontalScrollView，我明天再想办法，询问先别关闭，我们可以讨论一下

**Comment by Bamboy120315** [comment]
已经在群里了可以直接私聊我哈，在这上边聊不嗨
